imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

nelmio_api_doc: ~

fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false

lopi_pusher:
    app_id: 148502
    key: 4feeb2b96bccf23c91d8
    secret: 19930f14307bfaf345ac

    debug: true # true if you want use the debug of all requests
