services:

    stats.game.total:
        class: AppBundle\Stats\Game\TotalGameStats
        arguments: ["@repo.game"]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.game.gammon:
        class: AppBundle\Stats\Game\TotalGammonStats
        arguments: ["@repo.game"]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.game.backgammon:
        class: AppBundle\Stats\Game\TotalBackGammonStats
        arguments: ["@repo.game"]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.game.todaygames:
        class: AppBundle\Stats\Game\TodayTotalGamesStats
        arguments: ["@repo.game"]
        tags:
            - { name: stats.add }
        lazy: true
        public: false
