services:

    stats.player.mostplayedplayer:
        class: AppBundle\Stats\Player\MostPlayedPlayerStats
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.player.leastplayedplayer:
        class: AppBundle\Stats\Player\LeastPlayedPlayerStats
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.player.highestwinpercent:
        class: AppBundle\Stats\Player\PlayerWithHighestWinPercent
        arguments: [@repo.player]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.player.lowestwinpercent:
        class: AppBundle\Stats\Player\PlayerWithLowestWinPercent
        arguments: [@repo.player]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.player.total:
        class: AppBundle\Stats\Player\TotalPlayerStats
        arguments: [@repo.player]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.player.avg:
        class: AppBundle\Stats\Player\AverageEloStats
        arguments: [@repo.player]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false
