imports:
  - { resource: repositories.yml }
  - { resource: stats.yml }
  - { resource: eventlistener.yml }

services:
    elo.service:
        class: AppBundle\Service\EloService

    game.service:
        class: AppBundle\Service\GameService
        arguments: [@elo.service, @repo.game, @repo.player]

    twig.angular:
        class: ViewBundle\Twig\AngularTwig
        public: false
        tags:
            - { name: twig.extension }
