imports:
  - { resource: repositories.yml }
  - { resource: stats.yml }
  - { resource: eventlistener.yml }

services:
    game.service:
        class: AppBundle\Service\GameService
        arguments: [@repo.game, @repo.player]

    player.form.player_selector:
        class: AppBundle\Form\PlayerSelectorType
        arguments: [@repo.player]
        tags:
            - { name: form.type, alias: player_selector }

    twig.angular:
        class: ViewBundle\Twig\AngularTwig
        public: false
        tags:
            - { name: twig.extension }
