imports:
  - { resource: repositories.yml }
  - { resource: stats.yml }
  - { resource: eventlistener.yml }

services:
    game.service:
        class: AppBundle\Service\GameService
        arguments: [@repo.game, @repo.player]

    twig.angular:
        class: ViewBundle\Twig\AngularTwig
        public: false
        tags:
            - { name: twig.extension }
