services:

    stats.sp.allgames:
        class: AppBundle\Stats\SinglePlayer\AllGames
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.gamesprday:
        class: AppBundle\Stats\SinglePlayer\GamesPrDay
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.backgammons:
        class: AppBundle\Stats\SinglePlayer\TotalBackGammons
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.gammons:
        class: AppBundle\Stats\SinglePlayer\TotalGammons
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.games:
        class: AppBundle\Stats\SinglePlayer\TotalGames
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.winrate:
        class: AppBundle\Stats\SinglePlayer\WinRate
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.wins:
        class: AppBundle\Stats\SinglePlayer\Wins
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false

    stats.sp.lost:
        class: AppBundle\Stats\SinglePlayer\Lost
        arguments: [@repo.player, @repo.game]
        tags:
            -  { name: stats.add }
        lazy: true
        public: false
