<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{

    public function getManager()
    {
        return $this->_em;
    }

    /**
     * @return Player
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLowestWinPercent()
    {
        $builder = $this->createQueryBuilder('player');
        $builder->orderBy('player.winPercent', 'ASC');
        $builder->setMaxResults(1);
        return $builder->getQuery()->getSingleResult();
    }

    /**
     * @return Player
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getHighestWinPercent()
    {
        $builder = $this->createQueryBuilder('player');
        $builder->orderBy('player.winPercent', 'DESC');
        $builder->setMaxResults(1);
        return $builder->getQuery()->getSingleResult();
    }

}
